# Generated by Django 2.2.1 on 2019-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='Price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='rooms',
            name='free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='anoniem',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
