# Generated by Django 2.2.1 on 2019-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_myevent_myoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myoccurrence',
            name='event',
        ),
        migrations.DeleteModel(
            name='MyEvent',
        ),
        migrations.DeleteModel(
            name='MyOccurrence',
        ),
    ]
