# Generated by Django 2.2.1 on 2019-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20190606_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='roomnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
