# Generated by Django 2.2.1 on 2019-06-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20190606_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roomnumber', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='cleanshifts',
            name='date',
        ),
        migrations.AddField(
            model_name='cleanshifts',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cleanshifts',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cleanshifts',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
