# Generated by Django 2.2.1 on 2019-06-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20190606_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='free',
        ),
    ]
