# Generated by Django 2.2.1 on 2019-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_remove_rooms_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='person_space',
            new_name='capacity',
        ),
    ]
