# Generated by Django 2.2.1 on 2019-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_auto_20190607_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booked',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
