# Generated by Django 2.2.1 on 2019-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0009_auto_20190607_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='luxe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
