# Generated by Django 2.2.1 on 2019-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0010_rooms_luxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='phonenumber',
            field=models.CharField(default=12345678, max_length=10),
            preserve_default=False,
        ),
    ]
