# Generated by Django 2.2.1 on 2019-06-17 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_booked_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanshifts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cleanshifts',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cleanshifts',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
