# Generated by Django 2.2.1 on 2019-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_auto_20190617_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='payed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
