# Generated by Django 2.2.1 on 2019-06-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0013_booked_payed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Clipped',
        ),
    ]
