# Generated by Django 2.2.1 on 2019-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_auto_20190621_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='payment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
