# Generated by Django 2.2.1 on 2019-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0015_booked_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='payment_id',
            field=models.CharField(max_length=50),
        ),
    ]
