# Generated by Django 2.2.1 on 2019-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0016_auto_20190626_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='payed',
        ),
    ]
